class AppLocations {
  static const List<String> states = [
    'Maharashtra',
    'Gujarat',
    'Karnataka',
    'Madhya Pradesh',
    'Telangana',
    'Andhra Pradesh',
    'Tamil Nadu',
    'Uttar Pradesh',
    'Rajasthan',
    'Punjab',
    'Haryana',
    'Kerala',
    'Bihar',
    'West Bengal',
    'Odisha',
    'Assam',
    'Chhattisgarh',
    'Jharkhand',
    'Uttarakhand',
    'Himachal Pradesh',
    'Goa',
    'Delhi (UT)',
    'Jammu and Kashmir (UT)',
    'Ladakh (UT)',
    'Chandigarh (UT)',
    'Puducherry (UT)',
    'Other State',
  ];

  static const Map<String, List<String>> districtsMap = {
    'Maharashtra': [
      'Solapur',
      'Pune',
      'Nashik',
      'Chhatrapati Sambhajinagar',
      'Thane',
      'Kolhapur',
      'Satara',
      'Sangli',
      'Ahmednagar',
      'Nagpur',
      'Amravati',
      'Latur',
      'Nanded',
      'Jalgaon',
      'Dhule',
      'Raigad',
      'Ratnagiri',
      'Sindhudurg',
      'Palghar',
      'Beed',
      'Osmanabad (Dharashiv)',
      'Buldhana',
      'Yavatmal',
      'Wardha',
      'Bhandara',
      'Gondia',
      'Gadchiroli',
      'Chandrapur',
      'Hingoli',
      'Jalna',
      'Parbhani',
      'Washim',
      'Other District',
    ],
    'Gujarat': [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Gandhinagar',
      'Junagadh',
      'Anand',
      'Navsari',
      'Valsad',
      'Kheda',
      'Mehsana',
      'Patan',
      'Banaskantha',
      'Sabarkantha',
      'Panchmahal',
      'Dahod',
      'Amreli',
      'Kutch',
      'Other District',
    ],
    'Karnataka': [
      'Bengaluru Urban',
      'Bengaluru Rural',
      'Belagavi',
      'Mysuru',
      'Dharwad',
      'Kalaburagi',
      'Mangaluru (Dakshina Kannada)',
      'Udupi',
      'Hassan',
      'Shivamogga',
      'Tumakuru',
      'Mandya',
      'Davanagere',
      'Ballari',
      'Vijayapura',
      'Bagalkote',
      'Bidar',
      'Chitradurga',
      'Chikkamagaluru',
      'Kodagu',
      'Kolar',
      'Raichur',
      'Ramanagara',
      'Yadgir',
      'Other District',
    ],
    'Madhya Pradesh': [
      'Bhopal',
      'Indore',
      'Gwalior',
      'Jabalpur',
      'Ujjain',
      'Sagar',
      'Rewa',
      'Satna',
      'Ratlam',
      'Chhindwara',
      'Dewas',
      'Shivpuri',
      'Dhar',
      'Khargone',
      'Katni',
      'Morena',
      'Khandwa',
      'Sehore',
      'Hoshangabad',
      'Vidisha',
      'Other District',
    ],
    'Telangana': [
      'Hyderabad',
      'Rangareddy',
      'Medchal-Malkajgiri',
      'Warangal',
      'Nizamabad',
      'Karimnagar',
      'Khammam',
      'Nalgonda',
      'Mahabubnagar',
      'Sangareddy',
      'Adilabad',
      'Siddipet',
      'Suryapet',
      'Other District',
    ],
    'Andhra Pradesh': [
      'Visakhapatnam',
      'Vijayawada (NTR)',
      'Guntur',
      'Tirupati',
      'Kurnool',
      'Nellore (SPSR)',
      'Kakinada',
      'Anantapur',
      'Chittoor',
      'Kadapa (YSR)',
      'Eluru',
      'Prakasam',
      'Vizianagaram',
      'Srikakulam',
      'East Godavari',
      'West Godavari',
      'Other District',
    ],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tiruppur',
      'Erode',
      'Vellore',
      'Tirunelveli',
      'Thanjavur',
      'Kanchipuram',
      'Cuddalore',
      'Dindigul',
      'Kanyakumari',
      'Karur',
      'Nagapattinam',
      'Namakkal',
      'Nilgiris',
      'Pudukkottai',
      'Ramanathapuram',
      'Ranipet',
      'Tenkasi',
      'Theni',
      'Thiruvallur',
      'Thiruvarur',
      'Thoothukudi',
      'Tirupathur',
      'Tiruvannamalai',
      'Viluppuram',
      'Virudhunagar',
      'Other District',
    ],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur Nagar',
      'Agra',
      'Varanasi',
      'Prayagraj',
      'Ghaziabad',
      'Gautam Buddha Nagar (Noida)',
      'Meerut',
      'Bareilly',
      'Aligarh',
      'Gorakhpur',
      'Moradabad',
      'Saharanpur',
      'Ayodhya',
      'Jhansi',
      'Mathura',
      'Muzaffarnagar',
      'Banda',
      'Other District',
    ],
    'Rajasthan': [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Sikar',
      'Sri Ganganagar',
      'Pali',
      'Bharatpur',
      'Jhunjhunu',
      'Barmer',
      'Nagaur',
      'Churu',
      'Chittorgarh',
      'Jaisalmer',
      'Jhalawar',
      'Hanumangarh',
      'Other District',
    ],
    'Punjab': [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali (SAS Nagar)',
      'Hoshiarpur',
      'Pathankot',
      'Gurdaspur',
      'Sangrur',
      'Moga',
      'Firozpur',
      'Faridkot',
      'Kapurthala',
      'Mansa',
      'Other District',
    ],
    'Haryana': [
      'Gurugram',
      'Faridabad',
      'Panipat',
      'Ambala',
      'Karnal',
      'Hisar',
      'Rohtak',
      'Sonipat',
      'Panchkula',
      'Yamunanagar',
      'Kurukshetra',
      'Jhajjar',
      'Rewari',
      'Sirsa',
      'Jind',
      'Bhiwani',
      'Other District',
    ],
    'Kerala': [
      'Thiruvananthapuram',
      'Ernakulam (Kochi)',
      'Kozhikode',
      'Thrissur',
      'Kollam',
      'Palakkad',
      'Malappuram',
      'Kannur',
      'Alappuzha',
      'Kottayam',
      'Kasaragod',
      'Idukki',
      'Wayanad',
      'Pathanamthitta',
      'Other District',
    ],
    'Bihar': [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif (Nalanda)',
      'Rohtas',
      'Arrah (Bhojpur)',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra (Saran)',
      'Samastipur',
      'Other District',
    ],
    'West Bengal': [
      'Kolkata',
      'North 24 Parganas',
      'South 24 Parganas',
      'Howrah',
      'Hooghly',
      'Paschim Medinipur',
      'Purba Medinipur',
      'Murshidabad',
      'Nadia',
      'Darjeeling',
      'Jalpaiguri',
      'Malda',
      'Bankura',
      'Birbhum',
      'Purulia',
      'Cooch Behar',
      'Uttar Dinajpur',
      'Dakshin Dinajpur',
      'Other District',
    ],
    'Odisha': [
      'Khordha (Bhubaneswar)',
      'Cuttack',
      'Ganjam',
      'Sundergarh (Rourkela)',
      'Puri',
      'Balasore',
      'Sambalpur',
      'Mayurbhanj',
      'Bhadrak',
      'Bolangir',
      'Jharsuguda',
      'Jajpur',
      'Angul',
      'Kalahandi',
      'Koraput',
      'Other District',
    ],
    'Assam': [
      'Kamrup Metropolitan (Guwahati)',
      'Cachar (Silchar)',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Sonitpur (Tezpur)',
      'Kamrup',
      'Barpeta',
      'Dhubri',
      'Golaghat',
      'Lakhimpur',
      'Bongaigaon',
      'Karimganj',
      'Hailakandi',
      'Other District',
    ],
    'Chhattisgarh': [
      'Raipur',
      'Durg',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Rajnandgaon',
      'Jagdalpur (Bastar)',
      'Raigarh',
      'Ambikapur',
      'Dhamtari',
      'Mahasamund',
      'Janjgir-Champa',
      'Other District',
    ],
    'Jharkhand': [
      'Ranchi',
      'East Singhbhum (Jamshedpur)',
      'Dhanbad',
      'Bokaro',
      'Hazaribagh',
      'Deoghar',
      'Giridih',
      'Ramgarh',
      'Palamu',
      'Dumka',
      'West Singhbhum',
      'Other District',
    ],
    'Uttarakhand': [
      'Dehradun',
      'Haridwar',
      'Nainital',
      'Udham Singh Nagar',
      'Pauri Garhwal',
      'Tehri Garhwal',
      'Almora',
      'Pithoragarh',
      'Chamoli',
      'Uttarkashi',
      'Bageshwar',
      'Champawat',
      'Rudraprayag',
      'Other District',
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Kangra (Dharamshala)',
      'Mandi',
      'Solan',
      'Kullu',
      'Sirmaur',
      'Una',
      'Hamirpur',
      'Chamba',
      'Bilaspur',
      'Lahaul & Spiti',
      'Kinnaur',
      'Other District',
    ],
    'Goa': ['North Goa', 'South Goa', 'Other District'],
    'Delhi (UT)': [
      'New Delhi',
      'Central Delhi',
      'North Delhi',
      'South Delhi',
      'East Delhi',
      'West Delhi',
      'North East Delhi',
      'North West Delhi',
      'South East Delhi',
      'South West Delhi',
      'Shahdara',
      'Other District',
    ],
    'Jammu and Kashmir (UT)': [
      'Srinagar',
      'Jammu',
      'Anantnag',
      'Baramulla',
      'Udhampur',
      'Rajouri',
      'Kathua',
      'Pulwama',
      'Kupwara',
      'Budgam',
      'Poonch',
      'Kulgam',
      'Samba',
      'Ganderbal',
      'Bandipora',
      'Doda',
      'Reasi',
      'Kishtwar',
      'Ramban',
      'Shopian',
      'Other District',
    ],
    'Ladakh (UT)': ['Leh', 'Kargil', 'Other District'],
    'Chandigarh (UT)': ['Chandigarh', 'Other District'],
    'Puducherry (UT)': ['Puducherry', 'Karaikal', 'Mahe', 'Yanam', 'Other District'],
    'Other State': ['Other District'],
  };

  static const Map<String, List<String>> talukasMap = {
    // Solapur
    'Solapur': [
      'Pandharpur',
      'Malshiras',
      'North Solapur',
      'South Solapur',
      'Baramati',
      'Sangola',
      'Mohol',
      'Karmala',
      'Madha',
      'Akkalkot',
      'Mangalwedha',
      'Other Taluka',
    ],
    // Pune
    'Pune': [
      'Haveli',
      'Baramati',
      'Shirur',
      'Junner',
      'Maval',
      'Khed',
      'Purandar',
      'Ambegaon',
      'Bhor',
      'Mulshi',
      'Velhe',
      'Indapur',
      'Daund',
      'Other Taluka',
    ],
    // Nashik
    'Nashik': [
      'Niphad',
      'Malegaon',
      'Sinnar',
      'Satana (Baglan)',
      'Nashik',
      'Dindori',
      'Igatpuri',
      'Kalwan',
      'Yeola',
      'Nandgaon',
      'Chandwad',
      'Deola',
      'Surgana',
      'Peth',
      'Trimbakeshwar',
      'Other Taluka',
    ],
    // Chhatrapati Sambhajinagar
    'Chhatrapati Sambhajinagar': [
      'Aurangabad',
      'Paithan',
      'Gangapur',
      'Vaijapur',
      'Kannad',
      'Sillod',
      'Phulambri',
      'Khuldabad',
      'Soegaon',
      'Other Taluka',
    ],
    // Thane
    'Thane': [
      'Kalyan',
      'Bhiwandi',
      'Thane',
      'Murbad',
      'Shahapur',
      'Ulhasnagar',
      'Ambarnath',
      'Other Taluka',
    ],
    // Kolhapur
    'Kolhapur': [
      'Karveer',
      'Hatkanangale',
      'Shirol',
      'Kagal',
      'Radhanagari',
      'Bhudargad',
      'Ajara',
      'Chandgad',
      'Gadhinglaj',
      'Shahuwadi',
      'Panhala',
      'Gaganbawda',
      'Other Taluka',
    ],
    // Satara
    'Satara': [
      'Satara',
      'Karad',
      'Wai',
      'Mahabaleshwar',
      'Phaltan',
      'Koregaon',
      'Khatav',
      'Man',
      'Patan',
      'Jaoli',
      'Khandala',
      'Other Taluka',
    ],
    // Sangli
    'Sangli': [
      'Miraj',
      'Tasgaon',
      'Walwa (Islampur)',
      'Shirala',
      'Khanapur (Vita)',
      'Atpadi',
      'Jat',
      'Kadegaon',
      'Kavathe Mahankal',
      'Palus',
      'Other Taluka',
    ],
    // Ahmednagar
    'Ahmednagar': [
      'Nagar',
      'Rahuri',
      'Shrirampur',
      'Sangamner',
      'Kopargaon',
      'Akole',
      'Nevasa',
      'Shevgaon',
      'Pathardi',
      'Parner',
      'Karjat',
      'Jamkhed',
      'Rahata',
      'Shrigonda',
      'Other Taluka',
    ],
    // Nagpur
    'Nagpur': [
      'Nagpur Urban',
      'Nagpur Rural',
      'Kamptee',
      'Hingna',
      'Katol',
      'Kalameshwar',
      'Saoner',
      'Ramtek',
      'Parseoni',
      'Mauda',
      'Umred',
      'Kuhi',
      'Bhiwapur',
      'Narkhed',
      'Other Taluka',
    ],
    // Gujarat
    'Ahmedabad': ['Daskroi', 'Sanand', 'Dholka', 'Viramgam', 'Bavla', 'Detroj-Rampura', 'Mandal', 'Dhandhuka', 'Ranpur', 'Other Taluka'],
    'Surat': ['Chorasi', 'Olpad', 'Kamrej', 'Bardoli', 'Mandvi', 'Palsana', 'Mangrol', 'Umarpada', 'Mahuva', 'Other Taluka'],
    'Vadodara': ['Vadodara', 'Padra', 'Karjan', 'Dabhoi', 'Waghodia', 'Savli', 'Desar', 'Other Taluka'],
    'Rajkot': ['Rajkot', 'Paddhari', 'Lodhika', 'Kotda Sangani', 'Jasdan', 'Gondal', 'Jetpur', 'Dhoraji', 'Upleta', 'Other Taluka'],

    // Karnataka
    'Bengaluru Urban': ['Bengaluru North', 'Bengaluru South', 'Bengaluru East', 'Anekal', 'Other Taluka'],
    'Bengaluru Rural': ['Devanahalli', 'Doddaballapura', 'Hosakote', 'Nelamangala', 'Other Taluka'],
    'Belagavi': ['Chikkodi', 'Gokak', 'Bailhongal', 'Belagavi', 'Athani', 'Khanapur', 'Ramdurg', 'Raybag', 'Saundatti', 'Hukkeri', 'Other Taluka'],
    'Mysuru': ['Mysuru', 'Nanjangud', 'T.Narasipura', 'Hunsur', 'Periyapatna', 'K.R.Nagara', 'H.D.Kote', 'Other Taluka'],

    // Madhya Pradesh
    'Bhopal': ['Huzur', 'Berasia', 'Other Taluka'],
    'Indore': ['Indore', 'Mhow (Dr. Ambedkar Nagar)', 'Depalpur', 'Sanwer', 'Hatod', 'Other Taluka'],
    'Gwalior': ['Gwalior', 'Bhitarwar', 'Dabra', 'Morar', 'Other Taluka'],
    'Jabalpur': ['Jabalpur', 'Patan', 'Shahpura', 'Sihora', 'Panagar', 'Kundam', 'Other Taluka'],

    // Telangana
    'Hyderabad': [
      'Charminar',
      'Secunderabad',
      'Khairatabad',
      'Ameerpet',
      'Asifnagar',
      'Bahadurpura',
      'Bandlaguda',
      'Golconda',
      'Himayathnagar',
      'Marredpally',
      'Musheerabad',
      'Saidabad',
      'Shaikpet',
      'Other Taluka',
    ],
    'Warangal': ['Warangal', 'Khila Warangal', 'Hanamkonda', 'Kazipet', 'Inavolu', 'Other Taluka'],

    // Andhra Pradesh
    'Visakhapatnam': ['Visakhapatnam Urban', 'Visakhapatnam Rural', 'Anandapuram', 'Bheemunipatnam', 'Gajuwaka', 'Pedagantyada', 'Gopalapatnam', 'Pendurthi', 'Other Taluka'],
    'Vijayawada (NTR)': ['Vijayawada Urban', 'Vijayawada Rural', 'Ibrahimpatnam', 'Jaggayyapeta', 'Kanchikacherla', 'Mylavaram', 'Other Taluka'],

    // Tamil Nadu
    'Chennai': ['Egmore', 'Mylapore', 'Tondiarpet', 'Guindy', 'Mambalam', 'Velachery', 'Perambur', 'Purasawalkam', 'Aminjikarai', 'Alandur', 'Sholinganallur', 'Other Taluka'],
    'Coimbatore': ['Coimbatore North', 'Coimbatore South', 'Pollachi', 'Mettupalayam', 'Annur', 'Sulur', 'Other Taluka'],

    // Uttar Pradesh
    'Lucknow': ['Lucknow', 'Malihabad', 'Mohanlalganj', 'Bakshi Ka Talab', 'Sarojini Nagar', 'Other Taluka'],
    'Kanpur Nagar': ['Kanpur Sadar', 'Ghatampur', 'Bilhaur', 'Narwal', 'Other Taluka'],

    // Rajasthan
    'Jaipur': ['Jaipur', 'Amber', 'Sanganer', 'Bassi', 'Chaksu', 'Chomu', 'Jamwa Ramgarh', 'Kotputli', 'Phulera', 'Shahpura', 'Other Taluka'],
    'Jodhpur': ['Jodhpur', 'Luni', 'Osian', 'Phalodi', 'Piparcity', 'Shergarh', 'Other Taluka'],

    // Punjab
    'Ludhiana': ['Ludhiana East', 'Ludhiana West', 'Jagraon', 'Khanna', 'Payal', 'Samrala', 'Raikot', 'Other Taluka'],

    // Haryana
    'Gurugram': ['Gurugram', 'Sohna', 'Pataudi', 'Badshahpur', 'Manesar', 'Farrukhnagar', 'Other Taluka'],

    // Kerala
    'Thiruvananthapuram': ['Thiruvananthapuram', 'Chirayinkeezhu', 'Neyyattinkara', 'Nedumangad', 'Varkala', 'Kattakada', 'Other Taluka'],

    // Bihar
    'Patna': ['Patna Sadar', 'Danapur', 'Barh', 'Masaurhi', 'Paliganj', 'Phulwari Sharif', 'Bikram', 'Fatuha', 'Other Taluka'],

    // West Bengal
    'Kolkata': ['Kolkata Sadar', 'Alipore', 'Sealdah', 'Jadavpur', 'Behala', 'Other Taluka'],

    // Goa
    'North Goa': ['Bardez', 'Tiswadi', 'Bicholim', 'Pernem', 'Sattari', 'Other Taluka'],
    'South Goa': ['Salcete', 'Mormugao', 'Ponda', 'Quepem', 'Sanguem', 'Canacona', 'Dharbandora', 'Other Taluka'],

    // Fallbacks
    'Other District': ['Other Taluka'],
  };

  static const Map<String, List<String>> villagesMap = {
    // Pandharpur
    'Pandharpur': [
      'Ojewadi',
      'Kavathe',
      'Bhalwani',
      'Takarwan',
      'Wakhari',
      'Karkamb',
      'Gopalpur',
      'Bhoje',
      'Tarapur',
      'Shetphal',
      'Korti',
      'Ranzani',
      'Chincholi',
      'Isbavi',
      'Gadhegaon',
      'Machnur',
      'Umdage',
      'Other Village',
    ],
    // Malshiras
    'Malshiras': [
      'Natepute',
      'Akluj',
      'Velapur',
      'Piramachi',
      'Dahigaon',
      'Markalu',
      'Goradwadi',
      'Sadashivnagar',
      'Londhe',
      'Tandulwadi',
      'Other Village',
    ],
    // North Solapur
    'North Solapur': [
      'Soregaon',
      'Shelgi',
      'Kumathe',
      'Degaon',
      'Mulegaon',
      'Haglur',
      'Belati',
      'Shivdari',
      'Other Village',
    ],
    // South Solapur
    'South Solapur': [
      'Mandrup',
      'Boramani',
      'Hotgi',
      'Kumbhari',
      'Vinchur',
      'Musti',
      'Hatture',
      'Ahirwadi',
      'Other Village',
    ],
    // Baramati
    'Baramati': [
      'Katewadi',
      'Malegaon',
      'Dorlewadi',
      'Kanheri',
      'Sangvi',
      'Supe',
      'Pandare',
      'Undawadi',
      'Other Village',
    ],
    // Sangola
    'Sangola': [
      'Jawkhede',
      'Nazare',
      'Waki',
      'Watambare',
      'Mahud',
      'Kole',
      'Kadlas',
      'Medsingi',
      'Other Village',
    ],
    // Mohol
    'Mohol': [
      'Penur',
      'Kamti',
      'Kurul',
      'Anwali',
      'Pokharapur',
      'Shingoli',
      'Virwade',
      'Other Village',
    ],
    // Karmala
    'Karmala': ['Jeur', 'Kem', 'Chikki', 'Washim', 'Pophlaj', 'Other Village'],
    // Madha
    'Madha': ['Kurduvadi', 'Madha', 'Tembhurni', 'Modnimb', 'Khed', 'Other Village'],
    // Akkalkot
    'Akkalkot': ['Maindargi', 'Chapalgaon', 'Nagansur', 'Tadwal', 'Other Village'],
    // Mangalwedha
    'Mangalwedha': ['Borale', 'Marwade', 'Machnur', 'Nandeshwar', 'Other Village'],

    // Haveli
    'Haveli': [
      'Wagholi',
      'Uruli Kanchan',
      'Hadapsar',
      'Dhayari',
      'Nanded Phata',
      'Manjari',
      'Khadakwasla',
      'Narhe',
      'Loni Kalbhor',
      'Other Village',
    ],
    // Shirur
    'Shirur': ['Ranjangaon', 'Shikrapur', 'Nabal', 'Sanaswadi', 'Koregaon Bhima', 'Pabal', 'Other Village'],
    // Junner
    'Junner': ['Ozar', 'Narayanganj', 'Alepata', 'Otur', 'Junnar', 'Other Village'],
    // Maval
    'Maval': ['Lonavala', 'Kamshet', 'Vadgaon', 'Talegaon Dabhade', 'Malavli', 'Other Village'],
    // Khed
    'Khed': ['Chakan', 'Rajgurunagar', 'Alandi', 'Khed', 'Other Village'],
    // Purandar
    'Purandar': ['Saswad', 'Jejuri', 'Diwale', 'Other Village'],

    // Niphad
    'Niphad': ['Pimpalgaon', 'Lasalgaon', 'Ozar', 'Niphad', 'Ranwad', 'Other Village'],
    // Malegaon
    'Malegaon': ['Soyagaon', 'Dabhad', 'Camp', 'Zodge', 'Nimgaon', 'Other Village'],
    // Sinnar
    'Sinnar': ['Musalgaon', 'Wavi', 'Pangri', 'Sinnar', 'Gonde', 'Other Village'],

    // Chhatrapati Sambhajinagar
    'Aurangabad': ['Chitegaon', 'Waluj', 'Kanchanwadi', 'Shendra', 'Bajaj Nagar', 'Other Village'],
    'Paithan': ['Adul', 'Pachod', 'Bidkin', 'Paithan', 'Other Village'],

    // Thane
    'Kalyan': ['Dombivli East', 'Khadakpada', 'Titwala', 'Shahad', 'Katemanivali', 'Other Village'],
    'Bhiwandi': ['Anjur', 'Padgha', 'Kharbav', 'Kasheli', 'Other Village'],
    'Thane': ['Naupada', 'Majiwada', 'Ghodbunder', 'Vartak Nagar', 'Other Village'],

    // Kolhapur
    'Karveer': ['Kalamba', 'Uchgaon', 'Vadange', 'Gokul Shirgaon', 'Shiroli', 'Other Village'],
    'Hatkanangale': ['Ichalkaranji', 'Kabnoor', 'Korochi', 'Ruikar', 'Other Village'],

    // Satara & Sangli
    'Satara': ['Kodoli', 'Shahupuri', 'Limb', 'Mahuli', 'Other Village'],
    'Karad': ['Saidapur', 'Malkapur', 'Umbraj', 'Ohar', 'Other Village'],
    'Miraj': ['Sangli', 'Madhavnagar', 'Wanlesswadi', 'Kupwad', 'Other Village'],
    'Nagar': ['Kedgaon', 'Vilad Ghat', 'Bhingar', 'Other Village'],

    // Gujarat
    'Daskroi': ['Aslali', 'Bareja', 'Jetalpur', 'Lambha', 'Other Village'],
    'Sanand': ['Changodar', 'Virochannagar', 'Moraiya', 'Sanand', 'Other Village'],
    'Chorasi': ['Hazira', 'Ichhapore', 'Mora', 'Suvali', 'Other Village'],
    'Olpad': ['Sayan', 'Kudsad', 'Karasad', 'Olpad', 'Other Village'],

    // Karnataka
    'Devanahalli': ['Budigere', 'Vijayapura', 'Channarayapatna', 'Other Village'],
    'Doddaballapura': ['Tubagere', 'Doddabelavangala', 'Dharampura', 'Other Village'],
    'Chikkodi': ['Nipani', 'Sadalga', 'Examba', 'Chikkodi', 'Other Village'],
    'Gokak': ['Koujalgi', 'Ankalgi', 'Ghataprabha', 'Gokak', 'Other Village'],

    // MP
    'Huzur': ['Kolar Road', 'Karond', 'Bairagarh', 'Gandhi Nagar', 'Other Village'],
    'Indore': ['Rau', 'Manglia', 'Tillore', 'Pigdamber', 'Other Village'],

    // Goa
    'Bardez': ['Mapusa', 'Calangute', 'Candolim', 'Anjuna', 'Porvorim', 'Other Village'],
    'Tiswadi': ['Panaji', 'Taleigao', 'Bambolim', 'Old Goa', 'Caranzalem', 'Other Village'],

    // Fallback
    'Other Taluka': ['Other Village'],
  };

  static List<String> getDistricts(String state) {
    return districtsMap[state] ?? ['Other District'];
  }

  static List<String> getTalukas(String district) {
    return talukasMap[district] ?? ['Other Taluka'];
  }

  static List<String> getVillages(String taluka) {
    return villagesMap[taluka] ?? ['Other Village'];
  }
}
